### ISSUE TITLE
Very Taxing on Performance

### ISSUE THREAD

**Issue by TheSpookyCat** [thegreatstorm/rust_webrcon#2]
Since you are creating a **new connection for each command**, this is not only a very slow and inefficient way of doing it but also extremely taxing on the server. I would not recommend this be used in any production environment whatsoever.

**Comment by thegreatstorm** [comment]
You seem to misunderstand situation. This is an on demand websocket interaction, no lingering auth, so yes its going to create a new connection for each command. Not a console interacting live time with the server. Its main purpose is to do automation and quick responses. I don't seem to understand your theory regarding "very slow, and inefficient, and extremely taxing on the server" utilizing this rest api for my automation for my rust server.  As well as my working on my discord bot to utilize this same rest api. I have yet to discover any issues regarding peformance.
